apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-lab-deployment
  labels:
    app: static-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-lab
  template:
    metadata:
      labels:
        app: static-lab
    spec:
      containers:
      - name: static-lab-container
        image: bbsharma102001/bulbul-ecomm
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: static-lab-service
spec:
  type: NodePort
  selector:
    app: static-lab
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 80
      nodePort: 30007
